all: \
	iso/images/menu/menu.arc \
	iso/images/loading.tim \
	iso/images/fonts1.tim \
	iso/images/hud/hud0.tim \
	iso/images/hud/hud1.tim \
	iso/images/hud/hud0weeb.tim \
	iso/images/characters/bf/main.arc \
	iso/images/characters/bf/dead.arc \
	iso/images/characters/bf/weeb.arc \
	iso/images/characters/dad/main.arc \
	iso/images/characters/spook/main.arc \
	iso/images/characters/pico/main.arc \
	iso/images/characters/mom/main.arc \
	iso/images/characters/mom/hair.tim \
	iso/images/characters/bf/xmas.arc \
	iso/images/characters/xmasp/main.arc \
	iso/images/characters/senpai/main.arc \
	iso/images/characters/senpaim/main.arc \
	iso/images/characters/spirit/main.arc \
	iso/images/characters/tank/main.arc \
	iso/images/characters/tank/ugh.arc \
	iso/images/characters/tank/good.arc \
	iso/images/characters/gf/main.arc \
	iso/images/characters/gf/tut.arc \
	iso/images/characters/gf/weeb.arc \
	iso/images/characters/gf/speaker.tim \
	iso/images/characters/clucky/main.arc \
	iso/images/stages/week1/back.arc \
	iso/images/stages/week2/back.arc \
	iso/images/stages/week3/back.arc \
	iso/images/stages/week4/back.arc \
	iso/images/stages/week4/hench.arc \
	iso/images/stages/week5/back.arc \
	iso/images/stages/week6/back.arc \
	iso/images/stages/week6/back3.tim \
	iso/images/stages/week7/back.arc

iso/%.tim: iso/%.png
	tools/funkintimpak/funkintimpak $@ $<

iso/%.arc:
	tools/funkinarcpak/funkinarcpak $@ $^

# Menu
iso/images/menu/menu.arc: iso/images/menu/back.tim iso/images/menu/ng.tim iso/images/menu/story.tim iso/images/menu/title.tim

# BF
iso/images/characters/bf/main.arc: iso/images/characters/bf/bf0.tim iso/images/characters/bf/bf1.tim iso/images/characters/bf/bf2.tim iso/images/characters/bf/bf3.tim iso/images/characters/bf/bf4.tim iso/images/characters/bf/bf5.tim iso/images/characters/bf/bf6.tim iso/images/characters/bf/dead0.tim
iso/images/characters/bf/dead.arc: iso/images/characters/bf/dead1.tim iso/images/characters/bf/dead2.tim iso/images/characters/bf/retry.tim
iso/images/characters/bf/weeb.arc: iso/images/characters/bf/weeb0.tim iso/images/characters/bf/weeb1.tim

# Dad
iso/images/characters/dad/main.arc: iso/images/characters/dad/idle0.tim iso/images/characters/dad/idle1.tim iso/images/characters/dad/left.tim iso/images/characters/dad/down.tim iso/images/characters/dad/up.tim iso/images/characters/dad/right.tim

# Spook
iso/images/characters/spook/main.arc: iso/images/characters/spook/idle0.tim iso/images/characters/spook/idle1.tim iso/images/characters/spook/idle2.tim iso/images/characters/spook/left.tim iso/images/characters/spook/down.tim iso/images/characters/spook/up.tim iso/images/characters/spook/right.tim

# Pico
iso/images/characters/pico/main.arc: iso/images/characters/pico/idle.tim iso/images/characters/pico/hit0.tim iso/images/characters/pico/hit1.tim

# Mom
iso/images/characters/mom/main.arc: iso/images/characters/mom/idle0.tim iso/images/characters/mom/idle1.tim iso/images/characters/mom/left.tim iso/images/characters/mom/down.tim iso/images/characters/mom/up.tim iso/images/characters/mom/right.tim

# Xmas BF
iso/images/characters/bf/xmas.arc: iso/images/characters/bf/xmasbf0.tim iso/images/characters/bf/xmasbf1.tim iso/images/characters/bf/xmasbf2.tim iso/images/characters/bf/xmasbf3.tim iso/images/characters/bf/xmasbf4.tim iso/images/characters/bf/xmasbf5.tim iso/images/characters/bf/dead0.tim

# Xmas Parents
iso/images/characters/xmasp/main.arc: iso/images/characters/xmasp/idle0.tim iso/images/characters/xmasp/idle1.tim iso/images/characters/xmasp/idle2.tim iso/images/characters/xmasp/idle3.tim iso/images/characters/xmasp/lefta0.tim iso/images/characters/xmasp/lefta1.tim iso/images/characters/xmasp/leftb0.tim iso/images/characters/xmasp/leftb1.tim iso/images/characters/xmasp/downa0.tim iso/images/characters/xmasp/downa1.tim iso/images/characters/xmasp/downb0.tim iso/images/characters/xmasp/downb1.tim iso/images/characters/xmasp/upa0.tim iso/images/characters/xmasp/upa1.tim iso/images/characters/xmasp/upb0.tim iso/images/characters/xmasp/upb1.tim iso/images/characters/xmasp/righta0.tim iso/images/characters/xmasp/righta1.tim iso/images/characters/xmasp/rightb0.tim iso/images/characters/xmasp/rightb1.tim

# Senpai
iso/images/characters/senpai/main.arc: iso/images/characters/senpai/senpai0.tim iso/images/characters/senpai/senpai1.tim
iso/images/characters/senpaim/main.arc: iso/images/characters/senpaim/senpai0.tim iso/images/characters/senpaim/senpai1.tim

# Spirit
iso/images/characters/spirit/main.arc: iso/images/characters/spirit/spirit0.tim iso/images/characters/spirit/spirit1.tim

# Tank
iso/images/characters/tank/main.arc: iso/images/characters/tank/idle0.tim iso/images/characters/tank/idle1.tim iso/images/characters/tank/left.tim iso/images/characters/tank/down.tim iso/images/characters/tank/up.tim iso/images/characters/tank/right.tim
iso/images/characters/tank/ugh.arc: iso/images/characters/tank/ugh0.tim iso/images/characters/tank/ugh1.tim
iso/images/characters/tank/good.arc: iso/images/characters/tank/good0.tim iso/images/characters/tank/good1.tim iso/images/characters/tank/good2.tim iso/images/characters/tank/good3.tim

# GF
iso/images/characters/gf/main.arc: iso/images/characters/gf/gf0.tim iso/images/characters/gf/gf1.tim iso/images/characters/gf/gf2.tim
iso/images/characters/gf/tut.arc: iso/images/characters/gf/tut0.tim iso/images/characters/gf/tut1.tim
iso/images/characters/gf/weeb.arc: iso/images/characters/gf/weeb0.tim iso/images/characters/gf/weeb1.tim

# Clucky
iso/images/characters/clucky/main.arc: iso/images/characters/clucky/idle0.tim iso/images/characters/clucky/idle1.tim iso/images/characters/clucky/left.tim iso/images/characters/clucky/down.tim iso/images/characters/clucky/up.tim iso/images/characters/clucky/right.tim

# Week 1
iso/images/stages/week1/back.arc: iso/images/stages/week1/back0.tim iso/images/stages/week1/back1.tim

# Week 2
iso/images/stages/week2/back.arc: iso/images/stages/week2/back0.tim iso/images/stages/week2/back1.tim iso/images/stages/week2/back2.tim

# Week 3
iso/images/stages/week3/back.arc: iso/images/stages/week3/back0.tim iso/images/stages/week3/back1.tim iso/images/stages/week3/back2.tim iso/images/stages/week3/back3.tim iso/images/stages/week3/back4.tim iso/images/stages/week3/back5.tim

# Week 4
iso/images/stages/week4/back.arc: iso/images/stages/week4/back0.tim iso/images/stages/week4/back1.tim iso/images/stages/week4/back2.tim iso/images/stages/week4/back3.tim
iso/images/stages/week4/hench.arc: iso/images/stages/week4/hench0.tim iso/images/stages/week4/hench1.tim

# Week 5
iso/images/stages/week5/back.arc: iso/images/stages/week5/back0.tim iso/images/stages/week5/back1.tim iso/images/stages/week5/back2.tim iso/images/stages/week5/back3.tim iso/images/stages/week5/back4.tim iso/images/stages/week5/back5.tim

# Week6
iso/images/stages/week6/back.arc: iso/images/stages/week6/back0.tim iso/images/stages/week6/back1.tim iso/images/stages/week6/back2.tim

# Week 7
iso/images/stages/week7/back.arc: iso/images/stages/week7/back0.tim iso/images/stages/week7/back1.tim iso/images/stages/week7/back2.tim iso/images/stages/week7/back3.tim

# Rule to clean all .arc and .tim files
clean:
	echo "Cleaning .arc and .tim files:"
	find iso -type f \( -name "*.arc" -o -name "*.tim" \) -print -delete
